# Generated by Django 3.2.8 on 2021-12-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('way', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='password',
            field=models.IntegerField(),
        ),
    ]
